
services:
  scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler.Dockerfile
    volumes:
      - ./logs/:/app/logs/
      - ./start.sh:/app/start.sh
    ports:
      - 8080:8080
    env_file: "./.env"
    environment:
      - LEADER=true
      - SETUP=${SETUP}
      - LOGPATH=${LOGPATH}
    cap_add:
      - NET_ADMIN
    command: ["/app/start.sh"]
    depends_on:
      - generator
  follower:
    build:
      context: .
      dockerfile: ./docker/scheduler.Dockerfile
    volumes:
      - ./logs/:/app/logs/
      - ./start.sh:/app/start.sh
    env_file: "./.env"
    environment:
      - SETUP=${SETUP}
      - LOGPATH=${LOGPATH}
    cap_add:
      - NET_ADMIN
    command: ["/app/start.sh"]
    depends_on:
      - scheduler
  worker:
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    volumes:
      - ./logs/:/app/logs
      - ./start.sh:/app/start.sh
    env_file: "./.env"
    environment:
      - LOGPATH=${LOGPATH}
    cap_add:
      - NET_ADMIN
    command: ["/app/start.sh"]
    depends_on:
      - scheduler
  generator:
    build:
      context: .
      dockerfile: ./docker/taskgenerator.Dockerfile
    env_file: "./.env"
    environment:
      - LOGPATH=${LOGPATH}
      - TASK_RATE=${TASK_RATE}
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs/:/app/logs
