
services:
  scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler.Dockerfile
    volumes:
      - ./logs/:/app/logs/
    ports:
      - 8080:8080
    env_file: "./config"
  worker:
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    volumes:
      - ./logs/:/app/logs
    env_file: "./config"
    depends_on:
      - scheduler
